### ISSUE TITLE
BUG: Invalid type of value on settings.json

### ISSUE THREAD

**Issue by gyulkkajo** [SeungukShin/cscope-code#1]
Thanks for the extension. I found an error message on setting menu when I try to change values.
There are error messages under Extensions, Preview, and Auto setting.

"Settings has an ivalid type, expected "string". Fix in JSON

I am using vscode v1.45.1  on Linux.

I'd like to fix it myself but I'm not good at javascript things....
Thanks in ahead! :)

**Comment by SeungukShin** [comment]
Thank you for reporting a bug.
It's because I inserted default value with wrong type.
dacc78b will fix this issue and I attach the extension file which contains this commit.
Thank you.
[cscope-code-issue1.zip](https://github.com/SeungukShin/cscope-code/files/4735514/cscope-code-issue1.zip)

**Comment by gyulkkajo** [comment]
Thanks for the quick response! ;)
