### ISSUE TITLE
No way to erase the number of results in the cscope treeview

### ISSUE THREAD

**Issue by mgarg1** [seungukshin/cscope-code#23]
After a while there are number of results in treeview and there is no way to erase the results in the view. 
Any command like `clear terminal` will help

**Comment by seungukshin** [comment]
Sorry for belated reply. I added `cscope-code:clear` command for this. (https://github.com/seungukshin/cscope-code/commit/1673eab1ea2564e3a74cbc57510112be79ef6303)
