### ISSUE TITLE
Is there way to type cscope commands

### ISSUE THREAD

**Issue by DillionApple** [SeungukShin/cscope-code#6]
Is there a way to type cscope myself? like 'cs f g xxx'. This is useful when I want to query the symbol but the symbol is not touchable in the current file.

**Comment by SeungukShin** [comment]
Thank you for using cscope-code extension.
There are two kind of command to query a symbol - "Cscope Code: Difinition" and "Cscope Code: Difinition Input".
"Cscope Code: Difinition" command queries a word under the cursor, while "Cscope Code: Difinition Input" shows an input box with a word under the cursor for you to modify the word for the query.
All query commands have a query command with "Input" postfix, which allows you to modify a symbol to query.

**Comment by DillionApple** [comment]
Thanks, @SeungukShin.
Is this a new feature? How should I call this command? I can not find the "Cscope Code: Difinition Input" command in the VS Code's cscope-code extension page, or in the README of the project.

**Comment by DillionApple** [comment]
Okay, I found it and the shortcuts. The documentation needs to be completed, think I can help.
